[package]
name = "yhfp"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Copy Helix file paths to the system clipboard."
keywords = ["cli", "helix", "editor", "clipboard", "file-path"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
color-eyre = { workspace = true }
ytil_editor = { workspace = true }
ytil_hx = { workspace = true }
ytil_sys = { workspace = true }
ytil_wezterm = { workspace = true }
