[package]
name = "vpg"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Manage PostgreSQL credentials with Vault and connect."
keywords = ["cli", "postgresql", "vault", "credentials", "database"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
color-eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ytil_sys = { workspace = true }
ytil_tui = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }

[lints]
workspace = true
