[package]
name = "ytil_wezterm"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Query and control `WezTerm` panes and metadata."
keywords = ["wezterm", "terminal", "pane", "multiplexer", "integration"]
categories = ["command-line-utilities", "development-tools"]

[features]
fake = ["dep:fake"]

[dependencies]
color-eyre = { workspace = true }
fake = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
fake = { workspace = true }

[lints]
workspace = true
