[package]
name = "ytil_sys"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Work with system paths, time, clipboard, and files."
keywords = ["system", "time", "io", "environment", "platform"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
chrono = { workspace = true }
home = { version = "0.5" }
itertools = { version = "0.14" }
owo-colors = { workspace = true }
pico-args = { version = "0.5" }
rootcause = { workspace = true }
serde = { workspace = true }
ytil_cmd = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
