[package]
name = "ytil_git"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Inspect and manipulate lightweight Git repository state."
keywords = ["git", "repository", "vcs", "status", "helpers"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
chrono = { workspace = true }
color-eyre = { workspace = true }
git2 = { workspace = true }
reqwest = { version = "0.12", features = ["blocking"] }
ytil_cmd = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }
