[package]
name = "ytil_tui"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Provide minimal terminal prompt and selection helpers."
keywords = ["tui", "terminal", "prompt", "widgets"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
owo-colors = { workspace = true }
rootcause = { workspace = true }
skim = { version = "3" }
ytil_git = { workspace = true }

[lints]
workspace = true
