[package]
name = "evoke"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Format, lint, build, and deploy workspace binaries."
keywords = ["cli", "build", "automation", "deployment", "rust"]
categories = ["command-line-utilities", "development-tools"]

[lints]
workspace = true

[dependencies]
color-eyre = { workspace = true }
ytil_cmd = { workspace = true }
ytil_sys = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
rstest = { workspace = true }
