[package]
name = "fkr"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Generate interactive fake test data."
keywords = ["cli", "fake", "data", "generator", "testing", "development"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
fake = { workspace = true, features = ["uuid"] }
rootcause = { workspace = true }
strum = { workspace = true }
ytil_sys = { workspace = true }
ytil_tui = { workspace = true }

[lints]
workspace = true
