[package]
name = "tec"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Run workspace lint suite (clippy, dependency & manifest checks)."
keywords = ["cli", "check", "lints"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
color-eyre = { workspace = true }
nomicon = { workspace = true }
thiserror = { workspace = true }
ytil_cmd = { workspace = true }
ytil_git = { workspace = true }
ytil_system = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
