[package]
name = "ghl"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "List and interactively merge GitHub pull requests."
keywords = ["cli", "git", "github", "branch", "management"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
color-eyre = { workspace = true }
strum = { workspace = true }
ytil_git = { workspace = true }
ytil_github = { workspace = true }
ytil_system = { workspace = true }
ytil_tui = { workspace = true }
