[package]
name = "ytil_editor"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Launch and interact with Helix, Neovim, and WezTerm."
keywords = ["editor", "wezterm", "neovim", "helix", "integration"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
color-eyre = { workspace = true }
ytil_wezterm = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }

[lints]
workspace = true
