[package]
name = "idt"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Install language servers and development utilities."
keywords = ["cli", "installer", "development", "tools", "language-server"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
flate2 = { version = "1.1" }
owo-colors = { workspace = true }
rootcause = { workspace = true }
sha2 = { version = "0.10" }
tar = { version = "0.4" }
tempfile = { workspace = true }
ureq = { workspace = true }
xz2 = { version = "0.1" }
ytil_cmd = { workspace = true }
ytil_gh = { workspace = true }
ytil_sys = { workspace = true }
zip = { version = "7.4", default-features = false, features = ["deflate"] }

[dev-dependencies]
assert2 = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }

[lints]
workspace = true
