[package]
name = "idt"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Install language servers and development utilities."
keywords = ["cli", "installer", "development", "tools", "language-server"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
color-eyre = { workspace = true }
sha2 = { workspace = true }
tempfile = { workspace = true }
ureq = { workspace = true }
ytil_cmd = { workspace = true }
ytil_gh = { workspace = true }
ytil_sys = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }

[lints]
workspace = true
