[package]
name = "ytil_noxi"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Expose Neovim Lua modules backed by Rust utilities."
keywords = ["neovim", "nvim", "lua", "plugin", "rust", "editor"]
categories = ["command-line-utilities", "development-tools"]

[features]
mockall = ["dep:mockall"]
testing = []

[dependencies]
color-eyre = { workspace = true }
mockall = { version = "0.14", optional = true }
nvim-oxi = { git = "https://github.com/noib3/nvim-oxi", rev = "b1278b123dbac3908f2686ebed6fdadbfef15be1", features = [
  "neovim-nightly",
  "mlua",
] }
serde = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
