[package]
name = "gch"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Interactively stage or remove entries from Git index."
keywords = ["cli", "git", "github", "branch", "management"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
owo-colors = { workspace = true }
rootcause = { workspace = true }
strum = { workspace = true }
ytil_git = { workspace = true }
ytil_sys = { workspace = true }
ytil_tui = { workspace = true }

[lints]
workspace = true
