[package]
name = "yghfl"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Generate GitHub links for files open in Helix."
keywords = ["cli", "github", "helix", "editor", "links"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
color-eyre = { workspace = true }
url = { workspace = true }
ytil_editor = { workspace = true }
ytil_gh = { workspace = true }
ytil_git = { workspace = true }
ytil_hx = { workspace = true }
ytil_sys = { workspace = true }
ytil_wezterm = { workspace = true }

[dev-dependencies]
fake = { workspace = true }
temp-env = { version = "0.3" }
ytil_hx = { workspace = true, features = ["fake"] }
ytil_wezterm = { workspace = true, features = ["fake"] }
