[package]
name = "try"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Retry a command with success/failure tracking."
keywords = ["cli", "retry", "command", "automation", "testing"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
color-eyre = { workspace = true }
itertools = { workspace = true }
ytil_sys = { workspace = true }
