[package]
name = "oe"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Open files in an editor from `WezTerm` context."
keywords = ["cli", "editor", "wezterm", "neovim", "nvim", "helix"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
color-eyre = { workspace = true }
ytil_cmd = { workspace = true }
ytil_editor = { workspace = true }
ytil_sys = { workspace = true }
ytil_wezterm = { workspace = true }
