[package]
name = "ytil_cmd"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Execute system commands with structured error handling."
keywords = ["command", "process", "exec", "shell", "utilities"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
color-eyre = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }

[lints]
workspace = true
