[window]
startup_mode = "Maximized"
option_as_alt = "Both"

[scrolling]
history = 99999

[font]
normal.family = "PT Mono"
size = 16.5
offset = { x = 0, y = 7 }

[colors]
primary.background = "#002020"
primary.foreground = "#c9c9c9"
cursor = { text = "#000000", cursor = "#ffffff" }
selection = { text = "CellForeground", background = "#505257" }
normal.black = "#505257"
normal.red = "#ec635c"
normal.green = "#8ce479"
normal.yellow = "#ffaa33"
normal.blue = "#6a6adf"
normal.magenta = "#ff00ff"
normal.cyan = "#00ffff"
normal.white = "#c9c9c9"
bright.black = "#505257"
bright.red = "#ec635c"
bright.green = "#8ce479"
bright.yellow = "#ffaa33"
bright.blue = "#6a6adf"
bright.magenta = "#ff00ff"
bright.cyan = "#00ffff"
bright.white = "#c9c9c9"

[cursor]
blink_interval = 750
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }

[selection]
save_to_clipboard = false

[keyboard]
# Apparently `option_as_alt = "Both"` is not enough
bindings = [
  { key = "Left", mods = "Alt", chars = "\u001Bb" },
  { key = "Right", mods = "Alt", chars = "\u001Bf" },
]
