[package]
name = "gcu"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Manage Git branches with optional GitHub lookup."
keywords = ["cli", "git", "github", "branch", "management"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
color-eyre = { workspace = true }
url = { workspace = true }
ytil_git = { workspace = true }
ytil_gh = { workspace = true }
ytil_sys = { workspace = true }
ytil_tui = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
rstest = { workspace = true }
